/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileserver;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.SocketException;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author Codename-tkc
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form Intro
     */
    public Intro() {
        initComponents();
        addStuffForMe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FileServer");
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/fileserver/FSLogo.png"))).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 22, 32));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 60));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        new Thread(new Runnable(){
            public void run(){
                FileServerAnimations.animateText(jLabel17, "© Copyrights #tkctechonogies 2017");
            }
        }).start();

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 820, 70));

        jPanel3.setBackground(new java.awt.Color(17, 22, 32));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(17, 22, 32));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/horizontal_line_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("");

        jPanel4.setBackground(new java.awt.Color(17, 22, 32));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/multiply_filled_25px.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 578, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        new Thread(new Runnable(){
            public void run(){
                FileServerAnimations.animateText(jLabel3, "        FileServer Version 1.0.0 Alpha");
            }
        }).start();

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 50));

        jScrollPane1.setBackground(new java.awt.Color(36, 47, 65));
        jScrollPane1.setHorizontalScrollBar(null);

        jPanel7.setBackground(new java.awt.Color(36, 47, 65));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 153, 204));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/document_100px.png"))); // NOI18N
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("       Logs");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 170, 180));

        jPanel9.setBackground(new java.awt.Color(0, 153, 204));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/server_100px_2.png"))); // NOI18N
        jLabel6.setText("  ");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Server");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 20));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 170, 180));

        jPanel10.setBackground(new java.awt.Color(0, 153, 204));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/info_100px.png"))); // NOI18N
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Connect");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 170, 180));

        jPanel13.setBackground(new java.awt.Color(0, 153, 204));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/settings_100px.png"))); // NOI18N
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Settings");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 40));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 170, 180));

        jPanel14.setBackground(new java.awt.Color(0, 153, 204));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/help_filled_100px.png"))); // NOI18N
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Help");
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, 40));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 170, 180));

        jPanel15.setBackground(new java.awt.Color(0, 153, 204));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/wifi_100px.png"))); // NOI18N
        jPanel15.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Hotspot");
        jPanel15.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, -1));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, 180));

        jScrollPane1.setViewportView(jPanel7);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 820, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x,y,dx,dy,fx,fy;
   
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        x= evt.getXOnScreen();
        y=evt.getYOnScreen();
        fx=this.getX();
        fy=this.getY();
         jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        
        dx= evt.getXOnScreen()-x;
        dy=evt.getYOnScreen()-y;
        this.setLocation(dx+fx,dy+fy);
 
    }//GEN-LAST:event_jPanel3MouseDragged
 Connections connections;
    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
                jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
      jPanel4.setBackground(Color.red);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
         jPanel4.setBackground(jPanel3.getBackground());
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
          jPanel5.setBackground(jPanel1.getBackground());
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        jPanel5.setBackground(jPanel3.getBackground());
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    
    
    
    Boolean connectionIsOpen=false;
int dh,dw;
    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        this.setEnabled(false);
    if(!connectionIsOpen){
        try{ connections= new Connections();
     dh = this.getHeight() - connections.getHeight();
    dw = this.getWidth() - connections.getWidth();
      Point point = this.getLocation();
        connections.setLocation((int)point.getX()+ dw/2,(int)point.getY()+ dh/2);
        connections.setVisible(true);
       connectionIsOpen=true;
       }
       
      catch(Exception e){
          
      }}
    else{
        Point point = this.getLocation();
        connections.setLocation((int)point.getX()+ dw/2,(int)point.getY()+ dh/2);
        connections.setVisible(true);
    }
    
    }//GEN-LAST:event_jPanel15MouseClicked
Boolean serverIsOpen=false;
ServerInterface serverInterface;
int dh1,dw1;
    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
  if(!serverIsOpen){
            intro.setEnabled(false);
            serverInterface= new ServerInterface();
     dh1 = this.getHeight() - serverInterface.getHeight();
    dw1 = this.getWidth() - serverInterface.getWidth();
      Point point = this.getLocation();
        serverInterface.setLocation((int)point.getX()+ dw1/2,(int)point.getY()+ dh1/2);        
        serverInterface.setVisible(true);
       serverIsOpen=true;
     }
    else{
      intro.setEnabled(false);
        Point point = this.getLocation();
        serverInterface.setLocation((int)point.getX()+ dw1/2,(int)point.getY()+ dh1/2);
         serverInterface.setVisible(true);
    }
    }//GEN-LAST:event_jPanel9MouseClicked
static boolean logIsOpen=false;
static Log log;
static int dh2,dw2;
    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        if(!logIsOpen){
            intro.setEnabled(false);
            log = new Log();
            dh2=this.getHeight() - log.getHeight();
            dw2=this.getWidth() - log.getWidth();
            Point point = this.getLocation();
            log.setLocation((int) point.getX()+dw2/2,(int) point.getY()+dh2/2);
            log.setVisible(true);
            logIsOpen=true;
        }
        else{
            intro.setEnabled(false);
            Point point = this.getLocation();
            log.setLocation((int) point.getX()+dw2/2,(int) point.getY()+dh2/2);
            log.setVisible(true);
        }
        
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jPanel5MouseClicked
boolean settingsIsOpen=false;
Settings settings;
int settingsdh,settingsdw;
    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        if(!settingsIsOpen){
            intro.setEnabled(false);
            settings=new Settings();
            settingsdh=this.getHeight() - settings.getHeight();
            settingsdw=this.getWidth() - settings.getWidth();
            settings.setLocation((int) this.getLocation().x+settingsdw/2,(int) this.getLocation().y+settingsdh/2);
            settings.setVisible(true);
            settingsIsOpen=true;
        }
        else{
            intro.setEnabled(false);
            settings.setLocation((int) this.getLocation().x+settingsdw/2,(int) this.getLocation().y+settingsdh/2);
            settings.setVisible(true);
            settingsIsOpen=true;
        }
    }//GEN-LAST:event_jPanel13MouseClicked
boolean helpIsOpen=false;
int helpdh,helpdw;
Help help;
    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        if(!helpIsOpen){
            intro.setEnabled(false);
            help=new Help();
            helpdh=this.getHeight() - help.getHeight();
            helpdw=this.getWidth() - help.getWidth();
            help.setLocation((int) this.getLocation().x+helpdw/2,(int) this.getLocation().y+helpdh/2);
            help.setVisible(true);
            helpIsOpen=true;
        }
        else{
            intro.setEnabled(false);
            help.setLocation((int) this.getLocation().x+helpdw/2,(int) this.getLocation().y+helpdh/2);
            help.setVisible(true);
            helpIsOpen=true;
        }
    }//GEN-LAST:event_jPanel14MouseClicked
// AboutUS is replaced by connect NB;
    boolean aboutUsIsOpen=false;
Connect aboutUs;
int aboutUsdh,aboutUsdw;
    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        if(!aboutUsIsOpen){
            intro.setEnabled(false);
            aboutUs=new Connect();
            aboutUsdh=this.getHeight() - aboutUs.getHeight();
            aboutUsdw=this.getWidth() - aboutUs.getWidth();
            aboutUs.setLocation((int) this.getLocation().x+aboutUsdw/2,(int) this.getLocation().y+aboutUsdh/2);
            aboutUs.setVisible(true);
            aboutUsIsOpen=true;
        }
        else{
                   try {
                    aboutUs.jTextArea1.setText(IpAddressManager.getIpInterfaces());
                } catch (SocketException ex) {
                    aboutUs.jTextArea1.setText("An unexpected error occured. Close this window and try again");
                }
            intro.setEnabled(false);
            aboutUs.setLocation((int) this.getLocation().x+aboutUsdw/2,(int) this.getLocation().y+aboutUsdh/2);
            aboutUs.setVisible(true);
            aboutUsIsOpen=true;
        }
        
    }//GEN-LAST:event_jPanel10MouseClicked
Color color = new Color(0,153,204);
    /**
     * @param args the command line arguments
     */
 static Intro  intro;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
intro= new Intro();
int dy=dim.height  -intro.getSize().height;
int dx =dim.width -intro.getSize().width;
        intro.setLocation(dx/2, dy/2);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
               intro.setVisible(true);
//               This portion is to work on log so that it opens and stays in the background and can start getting info

                       if(!logIsOpen){
            log = new Log();
            dh2=intro.getHeight() - log.getHeight();
            dw2=intro.getWidth() - log.getWidth();
            Point point = intro.getLocation();
            log.setLocation((int) point.getX()+dw2/2,(int) point.getY()+dh2/2);
   
            logIsOpen=true;
        }
            }
        });
    }
      static public void setEnabled(){
 intro.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static final javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

     Color hovercolor  = new Color(51,181,229);
 Color normalcolor = new Color(0,153,204);
     
     private void addStuffForMe() {
JPanel[] jPanels = {jPanel8,jPanel13,jPanel9,jPanel14,jPanel10,jPanel15};   
        for (JPanel jPanel : jPanels) {
               new Thread(() -> {
                   Settings.shake(jPanel);
               }).start();
            jPanel.addMouseListener(new MouseListener(){
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
               
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    FileServerAnimations.interrupt=false;
//                    FileServerAnimations.inUse=true;
                                  new Thread(() -> {
                FileServerAnimations.zoom(jPanel);
               }).start();                                  
             jPanel.setBackground(hovercolor);
             Thread thread=null;
                                if(e.getComponent().equals(jPanel8)){
                       jLabel18.setText("View server operations");
                       
                      thread = new Thread(() -> {
                           FileServerAnimations.animateText(jLabel18,"View server operations");
                       });
                   }
                                else if(e.getComponent().equals(jPanel13)){
                       // jLabel18.setText("Personalize and customize your file sharing");
                   thread = new Thread(() -> {
                           FileServerAnimations.animateText(jLabel18,"Personalize and customize your file sharing");
                       });  
                   }
                                else if(e.getComponent().equals(jPanel9)){
                      // jLabel18.setText("Start the server to share files");
                     thread =  new Thread(() -> {
                           FileServerAnimations.animateText(jLabel18,"Start the server to share files");
                       });
                     
                   }
                         else if(e.getComponent().equals(jPanel14)){
                       //jLabel18.setText("Get anwers to your doubts and worries and info on how to contact us");
                       thread =    new Thread(() -> {
                           FileServerAnimations.animateText(jLabel18, "Get anwers to your doubts and worries and info on how to contact us");
                       });
                   }
                               else if(e.getComponent().equals(jPanel10)){
                    //   jLabel18.setText("Address to type on the browser of the connected device");
                  thread =    new Thread(() -> {
                           FileServerAnimations.animateText(jLabel18, "Address to type on the browser of the connected device");
                       });
                   }
                                else if(e.getComponent().equals(jPanel15)){
                       //jLabel18.setText("Create a wifi connection with your device");
                   thread =     new Thread(() -> {
                           FileServerAnimations.animateText(jLabel18, "Create a wifi connection with your device");
                       });
                   }
                        thread.start();
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    FileServerAnimations.interrupt=true;
                  //  FileServerAnimations.inUse=false;
            jLabel18.setText("");
                   jPanel.setBackground(normalcolor);
               
             //jPanel.setBackground(hovercolor);
              

                   
                }
            
            });
        }
    }
}
