/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileserver;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author Codename-tkc
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Log
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/fileserver/FSLogo.png"))).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 22, 32));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(17, 22, 32));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/multiply_filled_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Settings");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileserver/Settings_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 50));

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Entails putting in place password for login of clients. Password=");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 22));

        jLabel5.setIcon(null);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 24, -1, 48));
        if(SettingsManager.readSetting(SettingsManager.READ_WRITE_ACCESS).equals(SettingsManager.READ_WRITE_ACCESS_READ)){
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/fileserver/Toggle Off_30px.png")));
        }
        else if(SettingsManager.readSetting(SettingsManager.READ_WRITE_ACCESS).equals(SettingsManager.READ_WRITE_ACCESS_WRITE))
        {
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/fileserver/Toggle On_30px_1.png")));
        }
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 78, 638, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Allow read/write permission to files");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 23, 547, 31));

        jLabel6.setIcon(null);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, 48));
        if(SettingsManager.readSetting(SettingsManager.AUTH_ACCESS).equals(SettingsManager.AUTH_ACCESS_FALSE)){
            jLabel6.setIcon(new ImageIcon(getClass().getResource("/fileserver/Toggle Off_30px.png")));
        }
        else if(SettingsManager.readSetting(SettingsManager.AUTH_ACCESS).equals(SettingsManager.AUTH_ACCESS_TRUE))
        {
            jLabel6.setIcon(new ImageIcon(getClass().getResource("/fileserver/Toggle On_30px_1.png")));
        }

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 640, 31));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 638, 10));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Give access to your clients to modify files(delete,rename,move ... etc)");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 41, 560, 31));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 150, 10));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Require authentication");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 94, 547, 31));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Entails putting in place password for login of clients. Password=");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 22));

        jTextField2.setBackground(new java.awt.Color(36, 47, 65));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 150, 20));
        String xaskdhgyud2; //custom random name to avoid future conflicts
        if(!( xaskdhgyud2 = SettingsManager.readSetting(SettingsManager.AUTH_ACCESS_PASS)).equals(SettingsManager.AUTH_ACCESS_FALSE)){
            jTextField2.setEditable(false);
            jTextField2.setText(xaskdhgyud2);
        }
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 150, 10));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 638, 10));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("New address: xxx.xxx.xxx.xxx:<new port>.(default is 1998)");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 22));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Use custom connection port (0 to 6000)");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 170, 540, 31));

        jTextField3.setBackground(new java.awt.Color(36, 47, 65));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 150, 20));
        String xaskdhgyud; //custom random name to avoid future conflicts
        if(!( xaskdhgyud = SettingsManager.readSetting(SettingsManager.CUSTOM_PORT)).equals(SettingsManager.CUSTOM_PORT_STATUS_OFF)){
            jTextField3.setEditable(false);
            jTextField3.setText(xaskdhgyud);
        }
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 150, 10));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 638, 10));

        jLabel15.setIcon(null);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, 48));
        if(SettingsManager.readSetting(SettingsManager.CUSTOM_PORT).equals(SettingsManager.CUSTOM_PORT_STATUS_OFF)){
            jLabel15.setIcon(new ImageIcon(getClass().getResource("/fileserver/Toggle Off_30px.png")));
        }
        else if(SettingsManager.readSetting(SettingsManager.CUSTOM_PORT_STATUS).equals(SettingsManager.CUSTOM_PORT_STATUS_ON))
        {
            jLabel15.setIcon(new ImageIcon(getClass().getResource("/fileserver/Toggle On_30px_1.png")));
        }

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Require authentication");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 94, 547, 31));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Note : After making changes, if the server was on, restart it for the changes to take effect.");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 640, 31));
        new Thread(new Runnable(){
            public void run(){
                try{
                    Thread.sleep(1000);
                    shake(jLabel12);
                    shake(jLabel17);
                    Thread.sleep(5000);
                    jLabel12.setText("");
                    jLabel17.setText("");
                }
                catch(InterruptedException e){

                }
            }
        }).start();

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("           Before modyfing the value of an already on setting, turn it.");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 640, 31));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Color darkcolor = new Color(17,22,32);
Color lightcolor = new Color(36,47,65);
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(Color.red);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
         jPanel3.setBackground(darkcolor);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
Intro.setEnabled();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked
int dx,dy,fx,fy,x,y;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        fx= this.getX();
        fy=this.getY();
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();
        jPanel2.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        dx= evt.getXOnScreen()-x;
        dy=evt.getYOnScreen()-y;
        this.setLocation(fx+dx,fy+dy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        jPanel2.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        SettingsManager.echo("click");
        if(SettingsManager.readSetting(SettingsManager.AUTH_ACCESS).equals(SettingsManager.AUTH_ACCESS_TRUE)){
            if(SettingsManager.setAuthAccess(false,null))
            { jLabel6.setIcon(new ImageIcon(getClass().getResource(toggleButtonOff)));
             jTextField2.setEditable(true);
            }
            else notify("An unknown error occurred");
        }
        else if(SettingsManager.readSetting(SettingsManager.AUTH_ACCESS).equals(SettingsManager.AUTH_ACCESS_FALSE))
        {
            String value;
            if(!(value = jTextField2.getText()).equals("")){
                if(SettingsManager.setAuthAccess(true,value)){ jLabel6.setIcon(new ImageIcon(getClass().getResource(toggleButtonOn)));
                 jTextField2.setEditable(false);}
                else notify("An unknown error occurred");
            }
            else{
                notify("The corresponding field was left empty");
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked
String toggleButtonOn ="/fileserver/Toggle On_30px_1.png";
String toggleButtonOff="/fileserver/Toggle Off_30px.png";

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if(SettingsManager.readSetting(SettingsManager.READ_WRITE_ACCESS).equals(SettingsManager.READ_WRITE_ACCESS_READ)){   
                 if(SettingsManager.setWritable(true)) jLabel5.setIcon(new ImageIcon(getClass().getResource(toggleButtonOn))); 
                 else notify("An unknown error occurred");
                }
                else if(SettingsManager.readSetting(SettingsManager.READ_WRITE_ACCESS).equals(SettingsManager.READ_WRITE_ACCESS_WRITE))
                {
                   
                if(SettingsManager.setWritable(false)) jLabel5.setIcon(new ImageIcon(getClass().getResource(toggleButtonOff))); 
                 else notify("An unknown error occurred");
                }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
               // TODO add your handling code here:
         // TODO add your handling code here:
        SettingsManager.echo("click");
        if(SettingsManager.readSetting(SettingsManager.CUSTOM_PORT_STATUS).equals(SettingsManager.CUSTOM_PORT_STATUS_ON)){
            if(SettingsManager.setCustomPort(false,null)){ jLabel15.setIcon(new ImageIcon(getClass().getResource(toggleButtonOff)));
            jTextField3.setEditable(true);
            }
            else notify("An unknown error occurred");
        }
        else if(SettingsManager.readSetting(SettingsManager.CUSTOM_PORT_STATUS).equals(SettingsManager.CUSTOM_PORT_STATUS_OFF))
        {
            String value;
            if(!(value = jTextField3.getText()).equals("")){
               try{ if(Integer.parseInt(value) <= 60000){
                if(SettingsManager.setCustomPort(true,value)) {jLabel15.setIcon(new ImageIcon(getClass().getResource(toggleButtonOn)));
                jTextField3.setEditable(false);
                }
                else notify("An unknown error occurred");
                }
                else{
                    notify("wrong input value (does not fall in range) : "+value);
                }
            }catch(NumberFormatException e){
                 notify("wrong input value: "+value);
            } 
            }
            else{
                notify("The corresponding field was left empty");
            }
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                
                    
                
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private static javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void notify(String an_error_occured) {
        new Thread(new Runnable(){
            @Override
            public void run() {
           jLabel8.setText("ERROR : "+ an_error_occured);
                    shake(jLabel8);
            try{
                Thread.sleep(5000);
                jLabel8.setText("");
                
            }
            catch(InterruptedException e){
                
            }
            }
            
        }).start();
    
    }
    public static void shake(javax.swing.JComponent jLabel){
        assert jLabel !=null;
        Point location;
        try {
             location = jLabel.getLocation();
            for(int i=0;i<=15;i++){
            Thread.sleep(5);
            jLabel.setLocation(location.x + i, location.y);
            }
            location = jLabel.getLocation();
            for(int i=0;i<=15;i++){
            Thread.sleep(5);
            jLabel.setLocation(location.x - i, location.y);
            }    
                        location = jLabel.getLocation();
            for(int i=0;i<=15;i++){
            Thread.sleep(5);
            jLabel.setLocation(location.x - i, location.y);
            } 
                        location = jLabel.getLocation();
            for(int i=0;i<=15;i++){
            Thread.sleep(5);
            jLabel.setLocation(location.x + i, location.y);
            } 
        } catch (InterruptedException ex) {
          
        }
    }

}